### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 10mubeen** [multipaths/DiffuPath#2]
- [x] add an -omics file input reader (accepts .csv, .tsv,  .txt,...  ) and explanation in readme
- [x] give descriptions formats for networks readme 
- [x] copy readme to docs index.rst
- [x] complete collections/dumps
- [x] add fold changes 
- [x] add folder to resources with different input and network format examples
- [x] update url to example files in readme

**Comment by 10mubeen** [comment]
[ ] add folder to resources with different input and network format examples

**Comment by ddomingof** [comment]
@10mubeen close?
